import React from "react";

export default function PrivacyPolicyPage() {
	return (
		// A neutral, soft background provides contrast for the main content card.
		<div className="bg-slate-50 font-sans antialiased text-slate-800">
			<div className="container mx-auto max-w-4xl px-4 py-12 md:px-16">
				{/* The main content card with more padding and larger rounded corners. */}
				<div className="bg-white p-8 md:p-12 rounded-2xl shadow-lg">
					{/* Page Header */}
					<div className="pb-6 border-b border-slate-200">
						<h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 tracking-tight">
							Privacy Policy
						</h1>
						<p className="mt-2 text-base font-medium text-slate-500">
							Last Updated: June 11, 2025
						</p>
					</div>

					<div className="space-y-10 mt-10">
						<section>
							<h2 className="text-2xl font-semibold text-slate-800 border-b border-slate-200 pb-3 mb-4">
								1. Introduction
							</h2>
							<p className="text-slate-600 leading-relaxed">
								This Privacy Policy describes how we collect, use, and handle
								your information when you use the Cloud Vision Showcase (the
								"Service"). Your privacy is important to us and we are committed
								to protecting it.
							</p>
						</section>

						<section>
							<h2 className="text-2xl font-semibold text-slate-800 border-b border-slate-200 pb-3 mb-4">
								2. Information We Collect
							</h2>
							<p className="text-slate-600 leading-relaxed mb-5">
								We collect the following types of information:
							</p>
							<ul className="list-disc list-outside pl-5 space-y-3 text-slate-600">
								<li>
									<strong>Images You Provide:</strong> We collect the images you
									voluntarily upload for the sole purpose of analysis via the
									Google Vision API.
								</li>
								<li>
									<strong>Analysis Data:</strong> We collect and store the
									analysis results generated by the API, such as detected labels
									and colors, to display them back to you.
								</li>
								<li>
									<strong>Usage Data:</strong> Like most web services, our
									servers may automatically log anonymous technical information
									such as your IP address, browser type, and request timestamp
									to monitor for errors and ensure security.
								</li>
							</ul>
						</section>

						<section>
							<h2 className="text-2xl font-semibold text-slate-800 border-b border-slate-200 pb-3 mb-4">
								3. How We Use Your Information
							</h2>
							<p className="text-slate-600 leading-relaxed mb-5">
								We use the information we collect strictly to:
							</p>
							<ul className="list-disc list-outside pl-5 space-y-3 text-slate-600">
								<li>Provide, operate, and maintain the Service.</li>
								<li>
									Process your uploaded images and display the analysis results.
								</li>
								<li>
									Monitor for errors and improve the performance and security of
									the Service.
								</li>
							</ul>

							{/* This callout block makes the key promise stand out. */}
							<div className="mt-6 border-l-4 border-blue-500 bg-blue-50 p-4 rounded-r-lg">
								<p className="font-semibold text-blue-800">
									We will never sell, rent, or share your images or personal
									information with third parties for marketing purposes.
								</p>
							</div>
						</section>

						<section>
							<h2 className="text-2xl font-semibold text-slate-800 border-b border-slate-200 pb-3 mb-4">
								4. Data Storage, Security, and Retention
							</h2>
							<p className="text-slate-600 leading-relaxed">
								Your uploaded images and analysis data are stored on Google
								Cloud Platform (GCP). While we take reasonable measures to
								protect your information, no method of transmission or storage
								is 100% secure. As this is a portfolio project, we will
								periodically delete all uploaded images and associated data from
								our systems.
							</p>
						</section>

						<section>
							<h2 className="text-2xl font-semibold text-slate-800 border-b border-slate-200 pb-3 mb-4">
								5. Third-Party Services
							</h2>
							<p className="text-slate-600 leading-relaxed mb-5">
								This Service relies on Google Cloud Platform to function. Your
								data is processed by Google services, which are subject to
								Google's own privacy policies:
							</p>
							<ul className="list-disc list-outside pl-5 space-y-3 text-slate-600">
								<li>
									Google Cloud Storage, Functions, Vision API, Firestore, and
									Cloud Run.
								</li>
							</ul>
						</section>

						<section>
							<h2 className="text-2xl font-semibold text-slate-800 border-b border-slate-200 pb-3 mb-4">
								6. Contact Us
							</h2>
							<p className="text-slate-600 leading-relaxed">
								If you have any questions about this Privacy Policy, please
								contact us at{" "}
								<a
									href="mailto:jaron@neolite.ca"
									className="font-semibold text-blue-600 hover:underline"
								>
									jaron@neolite.ca
								</a>
								.
							</p>
						</section>
					</div>
				</div>
			</div>
		</div>
	);
}
